spring:
  profiles:
    active:
    - eurekaServer

---

spring:
  profiles: eurekaServer
  application:
    name: microcoloud-eureka

server:
  port: 7001

security:
  basic:
    enabled: true
  user:
    name: edmin
    password: mldnjava

eureka:
  #server:
    #enable-self-preservation: false
   # eviction-interval-timer-in-ms: 60000
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer1:7002/eureka,http://edmin:mldnjava@eurekaServer2:7003/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eurekaServer

---

server:
  port: 7002

spring:
  profiles: eurekaServer1
  application:
    name: microcoloud-eureka1

security:
  basic:
    enabled: true
  user:
    name: edmin
    password: mldnjava

eureka:
  #server:
   # enable-self-preservation: false
    #eviction-interval-timer-in-ms: 60000
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer:7001/eureka,http://edmin:mldnjava@eurekaServer2:7003/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eurekaServer1

---

server:
  port: 7003

spring:
  profiles: eurekaServer2
  application:
    name: microcoloud-eureka2

security:
  basic:
    enabled: true
  user:
    name: edmin
    password: mldnjava

eureka:
  #server:
   # enable-self-preservation: false
    #eviction-interval-timer-in-ms: 60000
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer:7001/eureka,http://edmin:mldnjava@eurekaServer1:7002/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eurekaServer2