server:
  port: 7001

spring:
  application:
    name: microcoloud-eureka   #在EUREKA页面中申明服务名称

security:
  basic:
    enabled: true
  user:
    name: edmin
    password: mldnjava

eureka:
  #server:
    #enable-self-preservation: false # 保护模式是否启用
   # eviction-interval-timer-in-ms: 60000 # 设置服务down服务的清理时间间隔
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer1:7002/eureka,http://edmin:mldnjava@eurekaServer2:7003/eureka
    register-with-eureka: false # 当前的微服务不注册到eureka服务中
    fetch-registry: false   # 不通过eureka获得服务的注册信息
  instance:
    hostname: eurekaServer