spring:
  profiles:
    active:
    - dev
    
---

spring:
  profiles: dev
  application:
    name: microcloud-consumer-dept

server:
  port: 80 

  
logging:
  level:
    microcloud.service: debug

feign:
  hystrix:
    enabled: true
  compression:
    request:
      mime-types:
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer:7001/eureka,http://edmin:mldnjava@eurekaServer1:7002/eureka,http://edmin:mldnjava@eurekaServer2:7003/eureka