spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
  zipkin:
    base-url: http://zipkin-server:4444
  sleuth:
    sampler:
      percentage: 1.0 # 抽样比率 默认为0.1
  application:
    name: zuulGateway
    

server:
  port: 9876
  
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eurekaServer:7001/eureka,http://edmin:mldnjava@eurekaServer1:7002/eureka,http://edmin:mldnjava@eurekaServer2:7003/eureka
  instance:
  #  lease-renewal-interval-in-seconds:
  #  lease-expiration-duration-in-seconds:
    instance-id: zuulGateway9876
    prefer-ip-address: true
 
zuul:
  ignored-services:
    "*"
  routes:
    microcloud-provider-company: /company-proxy/**
    microcloud-provider-dept: /dept-proxy/**
    
info:
  app.name: microCloud
  company.name: lyfkm.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
security:
  basic:
    enabled: true
  user:
    name: zdmin
    password: mldnjava